package models;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.io.Serializable;

public class Report implements Serializable {

    private static final long serialVersionUID = 1L;

    private int    reportId;
    private String reportType;
    private String generatedBy;
    private String reportContent;
    private String generatedAt;

    private static final DateTimeFormatter FORMATTER =
            DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");

    // Default constructor
    public Report() {
        this.generatedAt = LocalDateTime.now()
                               .format(FORMATTER);
    }

    // Parameterized constructor
    public Report(int reportId, String reportType,
                  String generatedBy, String reportContent) {
        this.reportId      = reportId;
        this.reportType    = reportType;
        this.generatedBy   = generatedBy;
        this.reportContent = reportContent;
        this.generatedAt   = LocalDateTime.now()
                                 .format(FORMATTER);
    }

    public int    getReportId()      { return reportId; }
    public String getReportType()    { return reportType; }
    public String getGeneratedBy()   { return generatedBy; }
    public String getReportContent() { return reportContent; }
    public String getGeneratedAt()   { return generatedAt; }

    public void setReportId(int reportId)
    { this.reportId = reportId; }
    public void setReportType(String reportType)
    { this.reportType = reportType; }
    public void setGeneratedBy(String generatedBy)
    { this.generatedBy = generatedBy; }
    public void setReportContent(String reportContent)
    { this.reportContent = reportContent; }
    public void setGeneratedAt(String generatedAt)
    { this.generatedAt = generatedAt; }

    @Override
    public String toString() {
        return "==============================\n"  +
               "Report ID    : " + reportId        + "\n" +
               "Report Type  : " + reportType      + "\n" +
               "Generated By : " + generatedBy     + "\n" +
               "Generated At : " + generatedAt     + "\n" +
               "------------------------------\n"  +
               reportContent                       + "\n" +
               "==============================";
    }
}