package models;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
 // Model class representing a Report entity.Used by ReportService and AuditService to store and display report data.
public class Report {
    private int reportId;
    private String reportType;      //  E.g., "DAILY", "MONTHLY", "EMPLOYEE", "SALES", "PURCHASE"
    private String generatedBy;     // username of who generated the report
    private String reportContent;   // the actual report body text
    private String generatedAt;     // timestamp when report was created

    private static final DateTimeFormatter FORMATTER =
            DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
    public Report() {
        this.generatedAt = LocalDateTime.now().format(FORMATTER);
    }
    public Report(int reportId, String reportType, String generatedBy, String reportContent) {
        this.reportId      = reportId;
        this.reportType    = reportType;
        this.generatedBy   = generatedBy;
        this.reportContent = reportContent;
        this.generatedAt   = LocalDateTime.now().format(FORMATTER);
    }
    public int getReportId() {
        return reportId;
    }
    public void setReportId(int reportId) {
        this.reportId = reportId;
    }
    public String getReportType() {
        return reportType;
    }

    public void setReportType(String reportType) {
        this.reportType = reportType;
    }

    public String getGeneratedBy() {
        return generatedBy;
    }

    public void setGeneratedBy(String generatedBy) {
        this.generatedBy = generatedBy;
    }

    public String getReportContent() {
        return reportContent;
    }

    public void setReportContent(String reportContent) {
        this.reportContent = reportContent;
    }

    public String getGeneratedAt() {
        return generatedAt;
    }

    public void setGeneratedAt(String generatedAt) {
        this.generatedAt = generatedAt;
    }
    @Override
    public String toString() {
        return "==============================\n" +
               "Report ID    : " + reportId      + "\n" +
               "Report Type  : " + reportType    + "\n" +
               "Generated By : " + generatedBy   + "\n" +
               "Generated At : " + generatedAt   + "\n" +
               "------------------------------\n" +
               reportContent                     + "\n" +
               "==============================";
    }
}