package models;

public class Report {

    private String reportId;
    private String reportType;
    private String generatedBy;
    private String generatedDate;
    private String content;

    public Report(String reportId, String reportType,
                  String generatedBy, String generatedDate,
                  String content) {
        this.reportId      = reportId;
        this.reportType    = reportType;
        this.generatedBy   = generatedBy;
        this.generatedDate = generatedDate;
        this.content       = content;
    }

    public String getReportId()      {
         return reportId; 
    }
    public String getReportType()    {
         return reportType; 
    }
    public String getGeneratedBy()   { 
        return generatedBy; 
    }
    public String getGeneratedDate() { 
        return generatedDate; 
    }
    public String getContent()       { 
        return content; 
    }

    public void setReportId(String reportId)
    { this.reportId = reportId; }

    public void setReportType(String reportType)
    { this.reportType = reportType; }

    public void setGeneratedBy(String generatedBy)
    { this.generatedBy = generatedBy; }

    public void setGeneratedDate(String generatedDate)
    { this.generatedDate = generatedDate; }

    public void setContent(String content)
    { this.content = content; }

    @Override
    public String toString() {
        return "\n==============================" +
               "\nReport ID    : " + reportId      +
               "\nReport Type  : " + reportType    +
               "\nGenerated By : " + generatedBy   +
               "\nDate         : " + generatedDate +
               "\n------------------------------" +
               "\nContent : \n"    + content       +
               "\n==============================\n";
    }
}